"""auto migration 20250810_220813

Revision ID: 2ba14171e7c8
Revises: e6fc82b94fae
Create Date: 2025-08-10 22:08:14.135063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ba14171e7c8'
down_revision: Union[str, Sequence[str], None] = 'e6fc82b94fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
